### ISSUE TITLE
Migration from Snarky to xJsnark

### ISSUE THREAD

**Issue by recursivesmelting** [recursivesmelting/rs-proof-lib#3]
After much toil and deliberation I think the best possible route is to avoid [Snarky](https://github.com/o1-labs/snarky/) and use [xJsnark](https://github.com/akosba/xjsnark) instead as a high-level DSL.

Snarky is nowhere near mature enough to meet our needs and the developers are preoccupied with their own project (Coda) to properly interact with us. While learning OCaml was fun, struggling with the Snarky code has been quite an ordeal and one I do not wish to repeat until Snarky matures.

The migration to xJsnark is going reasonably smooth and the general framework of the DSL is inviting and quick to setup.

One important point though is that, unlike Snarky, xJsnark does not seem to support Mnt4 and Mnt6 curves which one needs to develop recursive proofs. However, this seems rather easy to work around (fork xJsnark/Jsnark) in comparison to the seemingly insurmountable task of working with Snarky.

**Comment by TheRealBluesun** [comment]
I have concerns about xJsnark being written in Java, and recommend we investigate using libsnark directly in parallel.
